apiVersion: v1
data:
    password: ENC[AES256_GCM,data:PIroDUN52+4g18yu,iv:P8MTUNutZVfx+a9BhK2gVeGuBhcD+mzKC7n7hx5pS8M=,tag:3kD7fyDgltfrqnh+YIXfaQ==,type:str]
    user: ENC[AES256_GCM,data:FepSnk4pHdg=,iv:2jKxpaFNZBOPedyCeDRMCsVU1a9yh5D/mzJpxNtMTlc=,tag:jNP2dwV8hVB46/G//+7mSg==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSlAzc0ZwN01FRUh6VFJz
            RTUrYWl0QWV5cGE3U0VDSm0wZUxTWmFJVFY4CkpEZTFkUlhGTE5jbDVzRXBFOVNo
            eC95TENodTlNZDNNZ24rWkZGcjZHMmMKLS0tIGVWZzIxdFkyTFpRcDNUSUgvTVM5
            TFhQOFNHN1NNV3ZtNm02WU81bXk5NmcK43G5uY5bc6mDb1qxAEf3d+p3bog6VkGE
            8teup/YnyNunMoQwRZxjllvqXlceA9siS1tzdnY0AyWNXfiyLIq+LQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17645hagame7hrjtpdyafrmhkp72y6r9vdc06vk52fdjdvln58umqjskgx5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T03:32:13Z"
    mac: ENC[AES256_GCM,data:TzEOJ1Mn3bvqO6/ZzGMWkbLVk5TdTHj23ggdZROJGS7qIvtaH7aumf5DEvSytDpYDDfu4CDUlVALSvFk605yz4jMfTz+f/hct73/WHrAoePEI+S/O20K+G1AoZy8wNAwo4TJSkCUHey2Hww1Q5adV8drqM9VTvGri4Yprw0UPxs=,iv:MhVeShrKgRp1vgpK8u8IyyLlWSwlrB4+jPJj41ZOR+w=,tag:/SSt6GlLZ+f1FXn9fAQ+jw==,type:str]
    version: 3.13.2
