apiVersion: v1
data:
    password: ENC[AES256_GCM,data:lO95rqyiWwN6b8ZL,iv:S7yfdu2JW7RIZc0/ho53l7Lm+cyL+J/zAG69ZPN9Ukg=,tag:SemaeOK/506tGk/+xbPlRQ==,type:str]
    user: ENC[AES256_GCM,data:djGLnSynFTu+i6vF,iv:vbCCf+bucQyA98E3jPKrRxUKYCyVeBKpk7lyKS9Yme4=,tag:DCh/UIyK7glRkHwvWgffGA==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRTNkVzVuVmhibEhZempZ
            aFBuNGYrQmlvbWUzTThSdTlRY3RSVkdVUlZ3CkJYY3dMVmtnWUVjVzF0Z0NZVUZ4
            QjR1UlNBNElLeWY0VytIZis5YjVYU1kKLS0tIGV2YXArM2VmOStSM3BSV0xTUVc1
            OFI1dWFpS0ZZWFhYc1NCNDZuOHh6VEUKFIS4TzleIT184NPj4j/54cm93amsSh9K
            aGa12FQeHMqF8wVO3M+gME/DA+BrECYlxs/pw6L5TU3/+t4neuS6yQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y04aa748ugxwr0jlcygt56rts7h8escdjed8cpa346ru4utugpzsya5cph
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T00:20:26Z"
    mac: ENC[AES256_GCM,data:HeHHVI9C5fXaTV5Lg2kJsl8m+CZCK9i+0r8pm5HkZiOWM8tuuBZpG1d/9tLaNZ/rXclQ9+K5Dlrkl0O+xQV0FejYNBrtaYE4yH9D5fnv9kK5cgTeb5aPJ3++Rh708q38b+QOGajhFLzu3lqF4i10VKkHtmGpVyRid4fZjMG3sYo=,iv:G4QTWWIiaCue6jfl03giDEilPd19sCtqecly6Z4dpGA=,tag:05StL6w3F1fBTH6unqrvcA==,type:str]
    version: 3.13.2
