apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:/f+nwIEsCLlEyIQyoQnK0anmjgPGOF9kuc1CLZeMlOrvudOAkmDJj/JiaAzoJWJSmm9OL2HiiaHVkDNYg4zqFRHTC9msEZ79UqbLk1NcUAcgwro26VCNyPpKjxM6jhJdNF2hMjI1kaQb/KGRHMrFEB3WG53luaSw1GiVPfS0BsS+T3emvKDoNn8o6B25qj3YEYCRV9dpyc40wD+GQ/P3DXC+0yE0YRYXnyAshocnmIulJFQVkam2TImIeMhvykadwA0fQzjwbv2odQ1DaTLvFFge2M+QbqLk0Y4YNBkS2MEP+m45md5uY6pTT3E=,iv:unMcSebUKVZwG2uAsTQykCP/3AFVmlQCCT2eCBiNrDk=,tag:Ee6oQSxfJT4r1AUw5OUsxw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: audiobookshelf
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFa2JPVmtSTmtWR3E4VDla
            aCtIdGN3NWpRMUFFNitmWlZHL3FFQ0pkOWxvCmVsbS9WcmJERDh1OEI0UVh5Q0xU
            K2hXUFV4bXJTWS9zajJnY21mVzY5aGMKLS0tIHFzci9DYm1xUDA0aDd2ckZlQ1dS
            UkpCWlFuMDVKQndwRkN4blhUK1gxVzQK9Ur0BvYdr4EFSl0+argCk93Cu9dzl5SI
            O2Tdmhh3fbcPnfKqxw8gb7vtvwb4zuhHHf3xCjt9FqxuO4rRd91M9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y04aa748ugxwr0jlcygt56rts7h8escdjed8cpa346ru4utugpzsya5cph
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T03:59:59Z"
    mac: ENC[AES256_GCM,data:1AAEqODH/CQ9MMu+LzBXU7Q7Jl7blTFeHwwRU9wSl4xjQJHulV+D2sGEFTymrZknziJpZ0LJcaRrBxNC2MucxNKTcVHqsX40otXnpAhPCykngGi/D0tIm6vLeVLq8qKq399jX1OdLxn83+mWskcV2Nfn5pVWUiGeSQTcdsf+9yM=,iv:BAnFLkIXpL2pk+XiQyFB40/eYR18U/QmdI16wpBqzoI=,tag:GVJ4G5NW92BhaX/1qUpvQA==,type:str]
    version: 3.13.2
