apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:a8ppLT7bhUmJXwPy,iv:3ctNS3gzaO1olVhRo6yXWUMnhJRsRqI/FoOEM1xKTKw=,tag:cdh0hFUbwPDV1yq7jiz0Ag==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:jhzPVR2alYReZvwS,iv:TTdkTaN+y/Jsyjov8S1D1/vFY2GNfc/jUrrUZwFaBNA=,tag:+ZmHlwhvTIEHRkaR3FeIPA==,type:str]
kind: Secret
metadata:
    name: linkding-secrets
    namespace: linkding
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5aVYxbnJhcXY0Smh5M0x6
            Qjd0YUp4OFpxZTVST1VkS25VNHV4V2ZPWGpJClBrTGRuUVJ0eU0zZVo1WFJwYXp2
            N0FYTUZLNk4rS1VUcDBiOEl4dXVoY1kKLS0tIHhHclh5QkRQdnRaakx1NXJSeFlz
            S0xCWW1Fa0IzYnBNY0JjMitDb3o2aUUKvANLVi51gaIP3ytSfnKdHWATi3t31iJb
            mmywDNmektTKs2T0O7HHDn4QJBnNU/CZJA4tDT4H7CgM7a982VsZ2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y04aa748ugxwr0jlcygt56rts7h8escdjed8cpa346ru4utugpzsya5cph
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T00:39:05Z"
    mac: ENC[AES256_GCM,data:mbH/wncOK9zxCx87uKf8xj+cQChWQ/z4lf33snvbQwhlx3BgiaBblhkKaYTnObCnu9vqDS0/rGY317F58s3RfvM7aOGknScOV5CMQugtGcsLrg/FVMBQEdkr1zsFpDjl4xq05yMYqssZfHuq7Zr+Putj08dy6tW40ZiH0FLCCEA=,iv:zT6HnJ9PUfoCUPq6P0y93leBMu6l5cvqVG3yawDjG08=,tag:BnnS6x+UxVpXsd8BjeYbVQ==,type:str]
    version: 3.13.2
