apiVersion: v1
kind: Secret
metadata:
    name: test-secret
    namespace: linkding
type: Opaque
stringData:
    test-key: ENC[AES256_GCM,data:r0y0vdFDDIc8ag==,iv:+Div8ikfxO02fbC+gOqNXnqDjsD+VytAp6e79NxrQdg=,tag:GwA8i2UJ6ZuUCuuZnH89Fg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCOHR5VTIvUTVUVnpBMzNq
            cHN5cjhhZ0UzcGI0V09oTEpzTUtJMFY0bVJvCnZUMFU5dFlxSkxZY2VtTWR6dzkz
            MnRJenN1SGxDcVdmaDdQZHUvckNOd3cKLS0tIENtUU1uTlBHa0lWNUFwUURtSEFi
            R1hXU3RXdHAzdHpiUzJQa0hQM0ZOZFUK9FpZGrl2WQYsuDPGZL+gnGWByVe2ZzAg
            lX4IyNqJW3Zli+asmlOXY/toDk7SZ/qTxdYuspYUscBoRl+jjpM+ow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y04aa748ugxwr0jlcygt56rts7h8escdjed8cpa346ru4utugpzsya5cph
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T01:29:17Z"
    mac: ENC[AES256_GCM,data:nB0aZ+kXmes/t7jCQLp6DJjmnwiVDUM9+ZXCz12y8oji/m5e7bnGVinN33s0729GwP5huHfm60jlGYfFHq+C7ew0bSwNkXmBQO8U/6zkwW1FCFoDUuDTekBt1lca8jwTvZ8sbwoKRXpHawM8uqs8H09umrAO6WKcLRWjTMaXg+8=,iv:MSBtFUTEY1XTnprf9F1HlYWS7kQRzyg8XXNQsKkKc30=,tag:lsBRdzHpKnxD7dli+k1q4Q==,type:str]
    version: 3.13.2
