apiVersion: v1
data:
    8af42f28-4751-4c99-abf4-c098bf952cf3.json: ENC[AES256_GCM,data:0DZ8UoA6yz5Kl8iduXLN1Dvlvrh2J4AYfrq5TTgCVZDZ7ovzdi4Hkd3hoqRl39wwZ9kFir7OYrmoWHmacAdCCyPJuirhaX/v+Q/fPCPSqpn1au31r/UwMKGg0EmS3bE4aw/51qSHrhhJaB4iyJ73MClldsP2NmZllgGcLr8TmvmmZgxDALn9tJrLpALocDU49nCdtx53vLFPN6degO2AV4oo19gRiy8RuIYWqb3Ebq2ibg0uutyjfSLQympXwgP8O6ECcGzuw+0YE7+9P6V0l2e0iAUMwZl8/HHtQ8NQy+2AgB2HDk6bzhXec7k=,iv:BPg6ORbUjow8FF6TyQe+611ti/Tvo9rD/xP0PHpVxTA=,tag:LunfJS4Ky7kasyYake2p/Q==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: linkding
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuc0VndmY1d0plN3pZazQr
            ZFM5UERCbEo2RVU0dFRES242WGo0NVVnbEU4CmFOOUxCYUFiT2dzSExpWjE2Nm1Z
            UmVhak5hNy9CN1VDQjlmeVBsMG00dHMKLS0tIEt6MkI2YWp4MTZXQmR1NzZJUUpR
            TG8xNlh4N3ZSc21vQ0VEQU1BZHdSNGsKlmzTNigy6KkSOH5P8+Zy4p18IsIc0ZdX
            zRoNx5VbdHJu1m45Q/wCycO6SMtNA/jmeMwDeITsFhCNQh1DLwiwaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y04aa748ugxwr0jlcygt56rts7h8escdjed8cpa346ru4utugpzsya5cph
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T02:55:48Z"
    mac: ENC[AES256_GCM,data:eZ38aydNarDU4gXP2+n4aFIEVoTUxdv28XMRi4imYgcNM0A53lNAQs4vSpQ1slWrp8NQPtbpUa6ZXvFn2L/lU1DBg0NckWtG2n/YGtP9AekB8YPlrWkW8fywk3aqlHdB3fzdKk2qYXYQKsYWuG3MFdj86tUReLqM8vtm1YPm+BY=,iv:qAsm8ivDydQrxvE9HgS/N6GGpCUtMrxmMlqxT9Zhtao=,tag:IrAmXG/wcx43CLzDqvGX8w==,type:str]
    version: 3.13.2
