apiVersion: v1
data:
    password: ENC[AES256_GCM,data:OTAnX3GdFwcFEzXC,iv:1ZuZM1inw+zztNRq7OKMGmPUu/8OJo4amhukjLoiksc=,tag:v4dQnkEXAArzeN2KO+MChg==,type:str]
    user: ENC[AES256_GCM,data:8CqLGcZ4t7yijbg4,iv:DQd7jhCi7zk//nnFYT35VDof+MXWhvlj4m67u1bQsh8=,tag:sDoGQDv3UT8m1OOVFffrJw==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3MmZWSDB1eUVRWjAxcFA5
            YWRzVE1qN29URVJtRTBRVzFLbHlKLzRGdXhrCnMvWjJWQ1BmWUNWZ2I0cGFac1Vj
            TFY1amk1elAxWEl6dzNveHJ2Mmt2Y3cKLS0tIHdUL1hrdXNKUkFWY2QydUx3WGcx
            QUFjZjE4NFBCQ1FpVVh3NU52ZjZvQnMKccL9J/fVNmaVuC4vckgXfGBEMZflnCCy
            vk0krvg9E5U+96yYuYbbj3t6vHZ/xbiWl4nXAyUzbKgzjxfKaldc6w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y04aa748ugxwr0jlcygt56rts7h8escdjed8cpa346ru4utugpzsya5cph
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T01:17:27Z"
    mac: ENC[AES256_GCM,data:/MCFv5G/JLicF8d3dfAYWkN+tETlmSygilJkmWJLsdLIs//uQDEuR6nzmaIy3wxpIohEng7U5T6ST4UrALYzQQWrgI1HTCXPyC9cgS4zqBw26KwYSDlrDQr57Fa9gmHetIfwPreGNv/lI7AuNi0WuXyL57TkIy9nzh3mvxiUaCs=,iv:NWEMPLhiq4bUHwkIKIrjc7XmNenN0bFN+Nr3CSLONfI=,tag:ia6m76FFxhaFKN4oJIJNbg==,type:str]
    version: 3.13.2
