apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:/ECnt1GM0ToDXApE,iv:v4sGAo4wZVT20PuXT28yuFUxkJcYUZZ7o1uO9QE24G0=,tag:4J6H3J6oFrVo7p8fAVH4cg==,type:str]
kind: Secret
metadata:
    name: grafana-secret
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SFJSV1c2bEdDRXNkSUZx
            dG5XdVgyeklnTUYwRFdGeUtOQlhhQWhuYXhrCnpBRmNMSkk5bnI4WmF0NUM2bzJT
            d1BzMEh3elZjNjZvSndQRlpkaGZsL1EKLS0tIFEvUkhIb2k4ZUVNVkk1aFRNQW9X
            a1VURzBtK2RjTlB4Z2xGUE5CY09iTmsK5jQXJq1uXtF0dBdjMaP6LKiQfHyeHizR
            4sysXmY6D6fIY6csN1NhynGUt+zVdq9xLrWlESMUF5FjDZUV1XSRIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y04aa748ugxwr0jlcygt56rts7h8escdjed8cpa346ru4utugpzsya5cph
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T03:13:14Z"
    mac: ENC[AES256_GCM,data:yi6jwTnIRTR0EVU7lzIeK4i9nzMV6W85ZWrP4YVW1+WJkNApc19UZGRcKX33sKmBCdctONXECuxV3VR02/AE09aTNwdE+jROBsecKDvrrNNbMx20G6JOEhmeHQWXoNgdlrBLAUAoE/m6vD8cI0mrJP0+aq7/9YncTH/a9WWOQLM=,iv:GS9eQ9XTNy+hibLn+wJ4RY030eg1U5IrLy8ScUt8pjk=,tag:GcxSot9xkdgWZ/15rpqRbw==,type:str]
    version: 3.13.2
