apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:9obr0WZUDoSSW+K2mHxRAwzKMdNVzbMcXXzXc6Gc8Sed3K8dLDcwKOdqvc2PTZOPhKa1SJrMa6M=,iv:yzje/CS5TyD+xvfQJ4fU6r+82rESrp1wm+rb4u5rJhc=,tag:Glv1VzsX62EbnCDynFKlGg==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
    namespace: renovate
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMGhDWHFBN01YRWxYSXRN
            OHBLWU9yYmRQVzBZZGZrUDBjTDl0T29XL1Q0CnZKZ1pyRytha2ZWOVFWMGVtdHRD
            RUtNbTVIK2g0VjNBYy9YZ0Y4Zk1XeTAKLS0tIEZ3NVNSeW5hK1BkVEdrS2ZqSDZ1
            bVdaRGkxdW4vTEdnTlJqbU1EQmdJQWMK4D0SGqz1ooPa4Gejn0+s8S3LuxC/sZ4z
            Fuve8kSLaTVcnOufk5S9eTme3EfLe4aNCfrxhKXlsbJNOegyD7q92g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y04aa748ugxwr0jlcygt56rts7h8escdjed8cpa346ru4utugpzsya5cph
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T03:10:55Z"
    mac: ENC[AES256_GCM,data:yERrBVeKV20qqGYPALSEGsFiLWHwiIyQMynfImOvnR1dzJhWKs4z5faGFCGqkjGsP2guiN9zr0hPkdZQWnXiQn7szLC2jCNSw/jhXO3plTJPS4XlRSlN1UOPLy4hmU5Q3jgBqEYOcXNdNJ6ONNOB5O4pOFGXHTPhSwdArR3lESw=,iv:UukfyNfyi1Kgee3W+DL7iQYPwTiGoVRa1laWOjnAdag=,tag:2/0jrAYvQr0hKbTUCncMzQ==,type:str]
    version: 3.13.2
