apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:tRpJEnEINtkqo70h6wEa/a3ChOJJ/Gy8TbuZ8za7wvrEY7lBxS2/K2jvtClTsfPxfkXDtkiLB6yHr/bFck3hjFBB1XnOncxqgTlhjw==,iv:nCaN012CTvsfhYiLuejtGY+ytMmlJNdsYyVxrD7zJx4=,tag:VJ4QG9a9imyT9GIRBgnvIQ==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
    namespace: renovate
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dE1TWVB3eTZQSDN2RnIz
            aHhiZTB1SUVRVDJIZDJLR1ZCVXdDYkErb1M0CkpmYWxnRFc3VzA2UVNGME85Mkxz
            Z0ZvendRaTFvZEliNjdxcnkrUGZ0SWsKLS0tIE5CZHA3N2lRWVBCWnV0OGs5YUZM
            N2l0NWtUVm5FSVVpa1p1Sy9HUjhDb28KKujxXHQuBIorQ9Lc8X/SXi3DXalbrakg
            MnMDfu+ZEtXfP005aVXMc/dJwtKATgq+tYiy5Hf5csVhtF54DxM/9w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y04aa748ugxwr0jlcygt56rts7h8escdjed8cpa346ru4utugpzsya5cph
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T01:47:37Z"
    mac: ENC[AES256_GCM,data:uiAqVWx8STbLIq+CYfDIlgXH6jKKNcSrW0f6Z/tPISuiTNY+zJXNIBwa+wpOdp0I6DQ8mGuRNaprS1VbD7w4uuNiki0YQltZ8YvM5Zf2PzkXdFqhH5/zlLxBYQYHD7vd7jYFd9sWMDXKRslKLHY7cgXpckjDQkx9yfPd3cW7gow=,iv:s2LNwVk8KvrVc4iyqColyWoTRcI9A6mH0r8mPY3zS/U=,tag:3x/Ro2EiyFUXflYjvTWKPA==,type:str]
    version: 3.13.2
